# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  main_config = debug_x64

else ifeq ($(config),debug_x32)
  main_config = debug_x32

else ifeq ($(config),release_x64)
  main_config = release_x64

else ifeq ($(config),release_x32)
  main_config = release_x32

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := main

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

main:
ifneq (,$(main_config))
	@echo "==== Building main ($(main_config)) ===="
	@${MAKE} --no-print-directory -C . -f main.make config=$(main_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f main.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x32"
	@echo "  release_x64"
	@echo "  release_x32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   main"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"